### ISSUE TITLE
Modification after recent update

### ISSUE THREAD

**Issue by MostHated** [zvuc/firefox-sliding-bookmarks-bar#4]
Just in case anyone else has an issue on Linux or otherwise after an update yesterday, I had to change:

from:

```css
:root {
    --toolbar-offset-height: 40px;
  }
```
to:

```css
:root {
    --toolbar-offset-height: 60px;
  }
```
Thanks,
-MH
